name: Sound Recognition Control Python Application

on: [push]

jobs:
  Run-Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Create file
      run: |
        echo Hello World
        echo Hello World > test.txt
  Run-Windwos:
    runs-on: windows-latest
    steps:
    - name: Create file
      run: |
        echo Hello World
        echo Hello World > test.txt
