name: Sound Recognition Control Python Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create file
      run: |
        echo Hello World
        echo Hello World > test.txt
